[project]
name = "runbook-mcp-server"
version = "0.1.0"
description = "Runbook MCP server"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "httpx>=0.28.1",
    "mcp[cli]>=1.6.0",
    "pyyaml>=6.0.2",
]
